export enum RolePermissionsEnum {
    manageGroup = 'manageGroup',
    manageTextChannels = 'manageTextChannels',
    manageCategories = 'manageCategories',
    manageRoles = 'manageRoles',
    manageEvents = 'manageEvents',
    manageEmojis = 'manageEmojis',
    readAuditLog = 'readAuditLog',
    banUsers = 'banUsers',
    viewTextChannels = 'viewTextChannels',
    readMessages = 'readMessages',
    writeMessages = 'writeMessages',
    deleteMessages = 'deleteMessages',
    embedLinks = 'embedLinks',
    embedFiles = 'embedFiles',
    addReactions = 'addReactions',
    useEmojis = 'useEmojis',
    useExternalEmojis = 'useExternalEmojis',
    mentionDefaultRoles = 'mentionDefaultRoles',
    mentionCustomRoles = 'mentionCustomRoles',
    inviteUsers = 'inviteUsers',
    voiceConnect = 'voiceConnect',
    voiceSpeak = 'voiceSpeak',
    streamVideo = 'streamVideo',
    muteMembers = 'muteMembers',
    deafenMembers = 'deafenMembers',
    moveMembers = 'moveMembers',
}